name: PyUW12Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup environment
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y libtbb-dev libarmadillo-dev libopenblas-dev

    - name: Setup UV
      uses: astral-sh/setup-uv@v5
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        python-version: ${{matrix.python-version}}
        pyproject-file: "pyproject.toml"
    
    - name: Set up Python
      run: uv python install
  
    - name: Build PyUW12
      shell: bash -el {0}
      run: uv build

    - name: Install PyUW12
      shell: bash -el {0}
      run: uv sync --all-extras --dev

    - name: Run tests
      shell: bash -el {0}
      run: uv run pytest

    - name: Lint with ruff
      run: uv tool run ruff check
